### ISSUE TITLE
Dev access to production?

### ISSUE THREAD

**Issue by morgs** [praekeltfoundation/ways-of-working#12]
"Generally you will be given access to a machine that is to be used for QA and one that is to be used for the production environment."

Is this accurate, or is prod access for DevOps only?

**Comment by hedleyroos** [comment]
I believe trusted devs (ie. those with a track record of not breaking things) should be granted (temporary) access to production servers to investigate if things go wrong. There is a wealth of knowledge in log files and commands like top and free that the developer can interpret better than devops.

**Comment by morgs** [comment]
Perhaps without sudo then, unless specifically needed?

**Comment by hedleyroos** [comment]
I like that.

**Comment by smn** [comment]
I'm happy with non-sudo access for partners that we trust enough.

**Comment by morgs** [comment]
Updated the Puppet section.
