### ISSUE TITLE
Mention policy on ALLOWED_HOSTS in PWoW

### ISSUE THREAD

**Issue by highvoltage** [praekeltfoundation/ways-of-working#14]
11:24 < calston> and actually our ways of working needs "If you set ALLOWED_HOSTS in django you'll be murdered with a blunt stick"

**Comment by highvoltage** [comment]
Well, mention it more subtly than calston did, at least :smirk:

**Comment by calston** [comment]
... because we are always behind nginx anyway, and it's nice to add new hostnames that people come up with later without having to rebuild the entire codebase.

**Comment by morgs** [comment]
Addressed this in new platforms doc
