### ISSUE TITLE
Document JS Sandbox apps

### ISSUE THREAD

**Issue by morgs** [praekeltfoundation/ways-of-working#24]

**Comment by morgs** [comment]
@praekelt/vumi-core, what is the best URL (or set of URLs) to point dev partners at, to see our sandbox apps?

http://vumi-go.readthedocs.org/en/latest/sample-applications.html only shows Ushahidi and gmaps. I'm sure there is a lot more we could include.

**Comment by hodgestar** [comment]
Maybe http://vumi-jssandbox-toolkit.readthedocs.org/en/latest/ ?
